### ISSUE TITLE
Enable variable length SRRs

### ISSUE THREAD

**Issue by sbooeshaghi** [pachterlab/ffq#1]
Example: SRR578548

(SRR is length 9)
https://www.ebi.ac.uk/ena/browser/view/SRR578548

**Comment by Lioscro** [comment]
Removed digit length check in 6a05c55e34efc7693621442c2bb4b06fbc562d92

**Comment by sbooeshaghi** [comment]
Merged to master https://github.com/pachterlab/ffq/pull/10
