### ISSUE TITLE
conda installation

### ISSUE THREAD

**Issue by MichWeb75** [pachterlab/ffq#12]
Dear developers,
can you please add your software to bioconda. This helps a lot to use ffq within workflows using conda as software manager.

**Comment by druvus** [comment]
I have added a draft recipe to bioconda but I run into an issue with the misisng file "requirements.txt" that needs to be fixed first. 

The draft recipe for ffq could be found here: https://github.com/bioconda/bioconda-recipes/pull/29146

**Comment by sbooeshaghi** [comment]
The requirements.txt missing file issue was just fixed in 256ae7cda77f0da707a3ecfe26e371a95341dbed thanks for bringing it to our attention @druvus. Once `ffq` is added to bioconda this issue can be closed.

**Comment by druvus** [comment]
ffq is now added to BioConda (https://anaconda.org/bioconda/ffq)

**Comment by sbooeshaghi** [comment]
Awesome, thank you!

**Comment by sbooeshaghi** [comment]
@druvus it seems like the conda version is out of date. How can we go about ensuring that is stays up-to-date with the version that is on pip? (a recent issue brought this to my attention, https://github.com/pachterlab/ffq/issues/49)

**Comment by druvus** [comment]
@sbooeshaghi the Bioconda will detect new releases automatically and create a new PR to update the version in Bioconda. However the PR needs to be approved manually by a Bioconda member. During the summer this is a little bit slower process and in this case it took a week before it was approved [see #36329](https://github.com/bioconda/bioconda-recipes/pull/36329). Hopefully it will be faster for the next release when it is not holidays.

**Comment by sbooeshaghi** [comment]
Thank you!
