### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by Jigyasa3** [pachterlab/ffq#19]
Hi all!

Thank you for a great resource! I am using it to download the R1 reads of multiple bioprojects. I have created a text file with all the SRR ids associated with a bioproject, and feed that to `ffq` for download.

Code-
`while read line;do ffq --ftp ${line} | xargs curl -O ;done < 2-accession_list_PRJNA730929.txt`

where the `2-accession_list_PRJNA730929.txt` consists of -
SRR14583629
SRR14583630
SRR14583631
SRR14583632
SRR14583633

After generating output for ~100 SRR ids (out of 316 ids), I get the following error. Any suggestions?

Error-
`curl: (56) Recv failure: Connection reset by peer
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:11 --:--:--     0
curl: (28) Failed to connect to ftp.sra.ebi.ac.uk port 21: Connection timed out`

**Comment by sbooeshaghi** [comment]
This looks to me like a connection timeout for one of the files that curl is trying to download. Do you know which SRR generates an ftp link that results in the timeout?

**Comment by sbooeshaghi** [comment]
Closing since this is an issue with `cURL` and not `ffq`.
