### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by sbooeshaghi** [pachterlab/ffq#21]
- make links to `supplementary_files` files accessible via `--supplementary` (for example, like `--ftp`)
- implement file name -> filetype parsing
- implement class-based data structure for accessions and metadata

**Comment by agalvezm** [comment]
Contact NCBI to resolve inconsistency between website and API for Biosample accessions.
Example:

**SAMEA3449213**
- SRA accession in website (https://www.ncbi.nlm.nih.gov/biosample/?term=SAMEA3449213): ERS746775
- SRA accession using eutils efetch (https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=biosample&id=SAMEA3449213&rettype=fasta&retmode=xml) : SRS896780
