### ISSUE TITLE
fetchngs + ffq = <3 ?

### ISSUE THREAD

**Issue by Midnighter** [pachterlab/ffq#22]
Hi,

I saw your [thread on Twitter](https://twitter.com/lpachter/status/1522322188493197312). Congrats on the new release. I'm one of the people who created [fetchngs](https://github.com/nf-core/fetchngs), an nf-core nextflow pipeline for downloading FASTQ files from public archives.

We have discussed a few times that ffq might be a good fit to be used in the pipeline instead of our current scripts (mentioned [here](https://github.com/nf-core/fetchngs/pull/8#issuecomment-854538637) and also on the nf-core Slack). @drpatelh it seems to me that with the ability to supply multiple accessions at various levels, ffq might now be a good fit. I haven't fully perused ffq's source code yet but if there are any missing features, it makes more sense to me to contribute them here. Thus ffq would be further improved and we can drop all the scripts.

**Comment by drpatelh** [comment]
Agree 💯 . It would be awesome to leverage the functionality on offer in ffq if it fits our needs and to contribute back. It has been on my radar for a while now but haven't had the time to properly sit down and play with a prototype implementation. Some cool new features added recently too.

**Comment by lakigigar** [comment]
Hi @Midnighter and @drpatelh, 

Thanks for reaching out. We'd love to have you work with us on ffq. There are many ideas and improvements we have in mind, and we'll be happy to hear your suggestions as well. Your contributions will be most welcome. 

Lior
