### ISSUE TITLE
Tests framework `nose` no longer maintained

### ISSUE THREAD

**Issue by ewels** [pachterlab/ffq#30]
The `nose` testing library used in `ffq` is no longer maintained and was last updated in 2015. It [doesn't work with Python 3.10](https://github.com/nose-devs/nose/issues/1099) with an issue that will not be fixed.

It looks like most people have switched to [pytest](https://docs.pytest.org/en/7.1.x/), and there's even an automated tool to help the conversion: [nose2pytest](https://github.com/pytest-dev/nose2pytest). Is this something that would be of interest?

Phil

**Comment by ewels** [comment]
Ah, looks like pytest even has support for running nose tests out of the box: https://docs.pytest.org/en/7.1.x/how-to/nose.html#noseintegration

**Comment by sbooeshaghi** [comment]
We have migrated over to pytest with the help of @lauraluebbert. See https://github.com/pachterlab/ffq/pull/36/
