### ISSUE TITLE
PRJNA format Bioproject support

### ISSUE THREAD

**Issue by Nusob888** [pachterlab/ffq#34]
Many thanks the brilliant tool. 

I am just wondering if there is support for bio project IDs that begin with PRJNA. This does not appear to be recognised. 

Many thanks

**Comment by lakigigar** [comment]
Thanks for the suggestion, we will work on this shortly.

**Comment by georgiesamaha** [comment]
Also wondering if this is still in the works. Would be a really useful addition @lakigigar 

Thanks for ffq!

**Comment by franciscozorrilla** [comment]
Also agree that it would be great if ffq could recognize bioproject IDs, thank for the useful tool!
