### ISSUE TITLE
`--split` throws an error

### ISSUE THREAD

**Issue by telatin** [pachterlab/ffq#38]
when running on 0.2.1 the command
```
# Echo exemplifies the fact that my input is a list of IDs from a process
echo -e "SRR19440534\tSRR19440543" | grep . | xargs ffq --split -o T/
```
The program throws this error:
```
Traceback (most recent call last):
  File "/mnt/disk/miniconda3/bin/ffq", line 10, in <module>
    sys.exit(main())
  File "/mnt/disk/miniconda3/lib/python3.9/site-packages/ffq/main.py", line 245, in main
    with open(os.path.join(args.o, f'{result["accession"]}.json'),
TypeError: string indices must be integers
```

Notes:
* omitting `--split` works
* even `ffq --split -o T/ SRR19440534 SRR19440543` fails, but I wanted to supply my use case

**Comment by sbooeshaghi** [comment]
Thank you for the PR! For other readers, this issue has been resolved thanks to @telatin and is now in the `dev` branch (and is soon to be merged into `master`).
