### ISSUE TITLE
ERROR object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by FFinotello** [pachterlab/ffq#40]
Hello and many thanks for this much-needed tool!

I am getting a recurrent error on a few accessions, e.g.:

`ffq SRP301121`

leads to:

```
[2022-07-15 22:20:29,563]    INFO Parsing Study SRP301121
[2022-07-15 22:20:29,924]    INFO Getting Sample for SRP301121
[2022-07-15 22:20:29,926]    WARNING No samples found for study. Modify code to search through ENA
[2022-07-15 22:20:29,926]    ERROR object of type 'NoneType' has no len()
```

Would you have any suggestions to solve this issue?

Many thanks,
Francesca

**Comment by telatin** [comment]
Ciao! What version are you using? Updating to latest fixed it for me

**Comment by FFinotello** [comment]
Ciao Andrea! I am using version 0.2.1

**Comment by agalvezm** [comment]
Hello, thanks so much for bringing this to our attention. It seems like you have stumbled upon an accession whose downstream ids are not available through the eutils efetch tool. These are exceptions and are very rare. We have fixed this issue in the devel branch by re-routing those accessions through ENA.
```
pip uninstall ffq
pip install git+https://github.com/pachterlab/ffq.git@devel
ffq SRP301121
```
Thanks for using ffq!

**Comment by FFinotello** [comment]
Thank you very much for fixing this!
