### ISSUE TITLE
Add --version flag

### ISSUE THREAD

**Issue by andersgs** [pachterlab/ffq#43]
Hi. Thank you for `ffq`.

It would be good if it had a `--version` flag:

From the `argparse` docs you could do something like this:
```
from ffq import __version__ as version
...
    parser.add_argument('--version', action='version', version=f'%(prog)s {version}')
```

**Comment by sbooeshaghi** [comment]
Added ce9212c9110718b31ea0c89e77b1aff2f8dde83d. Thank you @andersgs for the contribution!
