### ISSUE TITLE
Conda version out of date

### ISSUE THREAD

**Issue by half-adder** [pachterlab/ffq#49]
Conda version is pretty out of date relative to PyPI version, some features did not work for me when I installed using conda.

**Comment by sbooeshaghi** [comment]
Huh, I don't know why that would be the case - I just asked the individual who helped get `ffq` on bioconda, https://github.com/pachterlab/ffq/issues/12#issuecomment-1219077585 let's see what he says. Thank you for letting me know.

**Comment by druvus** [comment]
The bioconda version should now be the latest version.

**Comment by sbooeshaghi** [comment]
Thank you!
