### ISSUE TITLE
How open are you to larger contributions?

### ISSUE THREAD

**Issue by Midnighter** [pachterlab/ffq#54]
Hi,

I mentioned in #22 that `ffq` could be a good fit for some of our work. I'm now at a point where it makes sense for me to look into this. I played a little with `ffq` and looked at the source code. I definitely see some possible optimizations in how requests are made (basically batching them rather than always making individual requests) and also regarding code organization.

There is already good traction for `ffq` so I was wondering how open you are to accepting some larger refactoring? It'd be good to know that someone is there to review and merge PRs before I start the work. Also having an understanding regarding your philosophy on additional dependencies etc. would be good. I'm open to have a call if that simplifies things.

**Comment by sbooeshaghi** [comment]
Hi @Midnighter,

Thank you for your interest. We are definitely open to larger refactoring efforts for `ffq`. I think its a good idea to get on a call to discuss what you had in mind and to coordinate a coherent vision. Please send us an email and we can find a time that works. Our contact can be found in the biorxiv preprint for the paper: https://www.biorxiv.org/content/10.1101/2022.05.18.492548v2.full

I look forward to working with you!

**Comment by Midnighter** [comment]
Hi,

I have written to you and @lakigigar. Please check your spam in case it has gone missing.
