### ISSUE TITLE
ffq

### ISSUE THREAD

**Issue by BaHole** [pachterlab/ffq#64]
ERROR 404 Client Error:  for url: https://www.ebi.ac.uk/ena/browser/api/xml/SRR17651862/

**Comment by Rosaceae-w** [comment]
Hi! I'm facing the same error now. Have you found out to fix it?

**Comment by BaHole** [comment]
> Hi! I'm facing the same error now. Have you found out to fix it?
I recognize it as a latency issue for data release, just wait a while.

**Comment by drelo** [comment]
I have the same using the example in the front page

```
ffq SRR9990627      
[2024-02-29 18:26:12,070]    INFO Parsing run SRR9990627
[2024-02-29 18:26:13,210]   ERROR 404 Client Error:  for url: https://www.ebi.ac.uk/ena/browser/api/xml/SRR9990627/
[2024-02-29 18:26:13,210]   ERROR Provided accession is invalid
usage: ffq [-h] [-o OUT] [-l LEVEL] [--ftp] [--aws] [--gcp] [--ncbi] [--split]
           [--verbose] [--version]
           IDs [IDs ...]
ffq: error: For possible failure modes, please see https://github.com/pachterlab/ffq#failure-modes

```

**Comment by Rosaceae-w** [comment]
> > Hi! I'm facing the same error now. Have you found out to fix it?
> > I recognize it as a latency issue for data release, just wait a while.

Ok, thanks! I'll wait a while and see how it goes.
