### ISSUE TITLE
ffq not working anymore (ffq: error)

### ISSUE THREAD

**Issue by rderelle** [pachterlab/ffq#67]
Hi,

thanks for developing ffq. It has been really helpful so far!

However, it doesn't seem to work anymore. The following command line used to output something and I'm now getting an error message:

> ffq SRR6046717
> [2024-03-01 22:19:28,054]    INFO Parsing run SRR6046717
> [2024-03-01 22:19:28,192]   ERROR 404 Client Error:  for url: https://www.ebi.ac.uk/ena/browser/api/xml/SRR6046717/
> [2024-03-01 22:19:28,192]   ERROR Provided accession is invalid
> usage: ffq [-h] [-o OUT] [-l LEVEL] [--ftp] [--aws] [--gcp] [--ncbi] [--split] [--verbose] [--version] IDs [IDs ...]
> ffq: error: For possible failure modes, please see https://github.com/pachterlab/ffq#failure-modes

Does it have to do with ncbi depreciating the SRA IDs?
Is there a work around?

Thanks in advance if you could help me.

**Comment by sbooeshaghi** [comment]
Please upgrade to v0.3.1 and this example will work. A change to the ENA database caused an error with ffq which has now been resolved.

https://pypi.org/project/ffq/0.3.1/

**Comment by rderelle** [comment]
Many thanks, it works!
