### ISSUE TITLE
unable to retrieve non-SRR runs (DRR and ERR runs)

### ISSUE THREAD

**Issue by kaylajohnson** [pachterlab/ffq#8]
Great tool! It works perfectly for the SRR runs I have attempted to fetch from SRA. However, when I try to fetch DRR or ERR runs, for example using ffq ERR3372842 > ERR3372842.json, I get this error: 
usage: ffq [-h] [-o OUT] [-t TYPE] [--split] [--verbose] IDs [IDs ...]
ffq: error: ERR3372842 failed validation. SRRs must start with 'SRR' and end with digits.

This problem could be because of how/where these samples are stored, in which case this is not necessarily an easy fix, but if it is an internal check you are doing, it is worth noting that some run accessions start with "ERR" and "DRR" - this Biostars question might be helpful in explaining the difference between SRR/ERR/DRR runs: https://www.biostars.org/p/381527/

Suggested solution: If there is an internal check giving this error, modify internal check to accept ERR/DRR run accessions. If it is not an internal check and ERR/DRR runs not easily accessible, I don't have a solution. 

Thank you!

**Comment by sbooeshaghi** [comment]
Thanks for pointing this out, we've received a few suggestions regarding various accession types, ENA in particular. I just need to make a small change to the `parse_run` function to allow for parsing DRR/ERR ID's. I'll make those changes and push them to the `devel` branch. I'll let you know when its ready.

**Comment by sbooeshaghi** [comment]
Ok, I just pushed to `devel`. If you clone the repo, checkout the `devel` branch, and pip install `ffq` from there, you'll be able to do 

`ffq -t ERR ERR3372842` and
`ffq -t ERP ERP115772`.

I can also add the ability to parse DRR if you could post an example accession. Thank you!

**Comment by kaylajohnson** [comment]
Wow, excellent response time, thank you! A few examples of DRR accessions would be DRR001173, DRR001640, DRR002597.

**Comment by sbooeshaghi** [comment]
Done. Please see the most recent commit in the `devel` branch.: https://github.com/pachterlab/ffq/commit/080dbad66a41d474f555d48b039bf365d0561085

**Comment by sbooeshaghi** [comment]
You can now install `ffq`, with this fix, directly from pip

```
pip install ffq==0.0.2
```
