### ISSUE TITLE
Incomplete output from DOI

### ISSUE THREAD

**Issue by GeoMicroSoares** [pachterlab/ffq#9]
Hi there,

Running `ffq -t DOI 10.1038/s41467-020-19648-2 -o test.json`, `ffq` parses 7 runs but only writes the last one - SRR12623522. Is there a way around this?

This is happening on ffq `0.0.1`.

Thanks!

**Comment by sbooeshaghi** [comment]
Thanks for the issue, this was a bug in how the run (SRR) numbers were being grouped by study (SRP). I have fixed it in the `devel` branch: https://github.com/pachterlab/ffq/commit/dbe4197f69e8eed2e7c5adfdd5457098a5a646df

I will be creating a new release to pypi soon. In the meantime you clone the repo, checkout the `devel` branch, and install the package like so:

```bash
git clone https://github.com/pachterlab/ffq.git
cd ffq
git checkout devel
pip install .
```

**Comment by sbooeshaghi** [comment]
You can now install `ffq`, with this fix, directly from pip

```
pip install ffq==0.0.2
```

**Comment by GeoMicroSoares** [comment]
Thanks for this - tested and it works with `0.0.2`!
